# Generated by Django 2.1.2 on 2018-11-13 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digitalmarket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('service', models.DecimalField(decimal_places=5, max_digits=6)),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=4, max_digits=6)),
                ('requirement', models.TextField()),
                ('gallery', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalmarket.Category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalmarket.Sub_Category')),
            ],
        ),
    ]
