# Generated by Django 2.1.2 on 2018-11-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphicdesign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('service', models.DecimalField(decimal_places=5, max_digits=6)),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
    ]
